#!/usr/bin/env python3
"""从 brand/tokens.json（唯一事实源）生成引擎用的派生物。
用法：
  tokens.py                     生成到 brand/generated/
  tokens.py --check             重新生成并与 brand/generated/ 比对；不一致退出码 1（手改生成物或改了 tokens 没重生成）
  tokens.py --tokens P --out D  指定输入与输出目录（测试用）
  tokens.py --equiv-pt PX WIDTH [--content-mm 182]
                                图等效字号：PX 像素字号在 viewBox 宽 WIDTH 的图里、按正文宽 182 mm 缩放后的磅值
生成物：
  tokens.css           CSS 变量（--dm-*）与 @page 规则，doc-render 内联进 HTML
  svg-palette.json     svgkit 调色板（与 svgkit.py 的 C 同形：色名 → stroke/fill/text）+ 品牌图风格（颜色键已解析为十六进制）
  mermaid-theme.json   Mermaid initialize 配置：theme base + themeVariables + 各图配置
  feishu-callouts.json 高亮块类型 → 飞书 callout 属性（emoji、background-color、border-color）与表头底色
退出码：0 成功；1 --check 不一致或 tokens.json 自检失败；2 用法错误。生成物不含时间戳，保证可比对。"""
import json, math, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TOKENS = os.path.join(ROOT, 'brand', 'tokens.json')
OUT = os.path.join(ROOT, 'brand', 'generated')
HEX = re.compile(r'^#[0-9A-Fa-f]{6}$')
PT_PER_MM = 72 / 25.4
GEN_NOTE = 'generated by doc-shared/scripts/tokens.py from brand/tokens.json; do not edit'


def equiv_pt(px, viewbox_width, content_mm=182.0):
    """图内 px 字号在 viewBox 宽为 viewbox_width 的图按正文宽 content_mm 缩放后的等效磅值。"""
    return px * content_mm / viewbox_width * PT_PER_MM


def min_px_for(pt, viewbox_width, content_mm=182.0):
    """要让等效字号不低于 pt，viewBox 宽 viewbox_width 的图内最小应使用的整数 px。"""
    return math.ceil(round(pt / PT_PER_MM * viewbox_width / content_mm, 6))


def selfcheck(t):
    errs = []
    colors = t.get('color', {})
    for k, v in colors.items():
        if not HEX.match(v): errs.append(f'color.{k} 不是 #RRGGBB：{v}')
    for name, p in t.get('palette', {}).items():
        for part in ('stroke', 'fill', 'text'):
            if not HEX.match(str(p.get(part, ''))): errs.append(f'palette.{name}.{part} 缺失或不是 #RRGGBB')
    hues = set(t.get('feishu', {}).get('hues', []))
    for name, c in t.get('callout', {}).items():
        for part in ('bg', 'border'):
            if c.get(part) not in colors: errs.append(f'callout.{name}.{part} 引用了不存在的颜色键 {c.get(part)}')
        bg = c.get('feishu_bg', '')
        m = re.match(r'^(light|medium)-(\w+)$', bg)
        if not (bg == 'gray' or (m and m.group(2) in hues)): errs.append(f'callout.{name}.feishu_bg 不是飞书合法高亮块底色：{bg}')
        if c.get('feishu_border') not in hues: errs.append(f'callout.{name}.feishu_border 不是飞书基础色相：{c.get("feishu_border")}')
    fig = t.get('figure', {})
    for grp in ('group', 'layer_emphasis'):
        for part, key in fig.get(grp, {}).items():
            if key not in colors: errs.append(f'figure.{grp}.{part} 引用了不存在的颜色键 {key}')
    for role, pal in fig.get('role_colors', {}).items():
        if pal not in t.get('palette', {}): errs.append(f'figure.role_colors.{role} 引用了不存在的调色板色 {pal}')
    min_node = min(fig.get('font_px', {}).values() or [0])
    w = fig.get('canvas_width_px', 1200)
    fmin = t.get('size', {}).get('figure_min', 7)
    if min_node and equiv_pt(min_node, w, t['page']['content_width_mm']) < fmin:
        errs.append(f'figure.font_px 最小 {min_node}px 在 {w} 宽画布上等效 {equiv_pt(min_node, w):.2f}pt，低于 size.figure_min {fmin}pt')
    return errs


def _stack(names, fallback=None):
    items = [f'"{n}"' if ' ' in n else n for n in names]
    return ','.join(items + ([fallback] if fallback else []))


def css(t):
    c, f, s, sp, lh, pg = t['color'], t['font'], t['size'], t['space'], t['line_height'], t['page']
    L = [f'/* {GEN_NOTE} */', f'@page{{size:{pg["size"]};margin:{sp["page_margin_top"]}mm {sp["page_margin_x"]}mm {sp["page_margin_bottom"]}mm}}', ':root{']
    for k, v in c.items(): L.append(f'  --dm-color-{k.replace("_", "-")}:{v};')
    L.append(f'  --dm-font-body:{_stack(f["cjk"] + f["latin"], f["fallback"])};')
    L.append(f'  --dm-font-cjk:{_stack(f["cjk"], f["fallback"])};')
    L.append(f'  --dm-font-latin:{_stack(f["latin"], f["fallback"])};')
    L.append(f'  --dm-font-mono:{_stack(f["mono"], "monospace")};')
    for k, v in s.items():
        if k == 'unit': continue
        L.append(f'  --dm-size-{k.replace("_", "-")}:{v}{s["unit"]};')
    for k, v in lh.items(): L.append(f'  --dm-line-height-{k.replace("_", "-")}:{v};')
    for k, v in sp.items():
        if k == 'unit': continue
        L.append(f'  --dm-space-{k.replace("_", "-")}:{v}{sp["unit"]};')
    L.append(f'  --dm-page-content-width:{pg["content_width_mm"]}mm;')
    L.append(f'  --dm-page-landscape-content-width:{pg["landscape_content_width_mm"]}mm;')
    for name, cl in t['callout'].items():
        L.append(f'  --dm-callout-{name}-bg:{c[cl["bg"]]};')
        L.append(f'  --dm-callout-{name}-border:{c[cl["border"]]};')
    L.append('}')
    return '\n'.join(L) + '\n'


def svg_palette(t):
    c, fig = t['color'], dict(t['figure'])
    fig.pop('note', None)
    resolved = {
        'canvas_width_px': fig['canvas_width_px'], 'margin_px': fig['margin_px'], 'gap_px': fig['gap_px'],
        'font_family': ', '.join(fig['font_family']), 'font_px': fig['font_px'], 'radius_px': fig['radius_px'],
        'stroke_px': fig['stroke_px'], 'dash': fig['dash'], 'arrowhead_px': fig['arrowhead_px'],
        'group': {k: c[v] for k, v in fig['group'].items()},
        'layer_emphasis': {k: c[v] for k, v in fig['layer_emphasis'].items()},
        'role_colors': fig['role_colors'],
        'text': {'title': c['ink'], 'subtitle': c['muted'], 'body': c['ink_2'], 'legend': c['muted']},
        'background': c['white'],
        'min_font_pt': t['size']['figure_min'],
        'min_font_px_at_canvas': min_px_for(t['size']['figure_min'], fig['canvas_width_px'], t['page']['content_width_mm']),
    }
    return {'_generated': GEN_NOTE, 'palette': t['palette'], 'figure': resolved}


def mermaid_theme(t):
    c, fig = t['color'], t['figure']
    fs = min_px_for(t['size']['figure_min'], fig['mermaid_ref_width_px'], t['page']['content_width_mm'])
    family = ', '.join(fig['font_family'])
    tv = {
        'fontFamily': family, 'fontSize': f'{fs}px',
        'background': c['white'], 'textColor': c['ink'], 'titleColor': c['ink'], 'lineColor': c['muted'],
        'primaryColor': c['tint'], 'primaryBorderColor': c['primary'], 'primaryTextColor': c['ink'],
        'secondaryColor': c['info_tint'], 'secondaryBorderColor': c['info'], 'secondaryTextColor': c['ink'],
        'tertiaryColor': c['surface_2'], 'tertiaryBorderColor': c['border'], 'tertiaryTextColor': c['ink'],
        'mainBkg': c['tint'], 'nodeBorder': c['primary'], 'clusterBkg': c['surface_2'], 'clusterBorder': c['border'],
        'edgeLabelBackground': c['white'],
        'noteBkgColor': c['warn_tint'], 'noteBorderColor': c['warn'], 'noteTextColor': c['ink'],
        'actorBkg': c['tint'], 'actorBorder': c['primary'], 'actorTextColor': c['ink'], 'actorLineColor': c['muted'],
        'signalColor': c['ink_2'], 'signalTextColor': c['ink'],
        'labelBoxBkgColor': c['tint'], 'labelBoxBorderColor': c['primary'], 'labelTextColor': c['ink'],
        'activationBkgColor': c['info_tint'], 'activationBorderColor': c['info'],
        'sectionBkgColor': c['tint'], 'altSectionBkgColor': c['white'], 'taskBkgColor': c['primary'],
        'taskBorderColor': c['primary_dark'], 'taskTextColor': c['white'], 'gridColor': c['border'],
        'critBkgColor': c['danger'], 'critBorderColor': c['danger'], 'doneTaskBkgColor': c['surface'],
    }
    return {
        '_generated': GEN_NOTE,
        '_note': f'fontSize 由 size.figure_min={t["size"]["figure_min"]}pt 按参考宽 {fig["mermaid_ref_width_px"]}px、正文宽 {t["page"]["content_width_mm"]}mm 反推；实际 SVG 更宽时仍须由 doc-figures 逐图算等效字号。gantt 的 axisFormat、tickInterval 与 htmlLabels=false 去 foreignObject 的效果未验证，1c 实测。',
        'startOnLoad': False, 'theme': 'base', 'securityLevel': 'strict', 'htmlLabels': False,
        'themeVariables': tv,
        'flowchart': {'htmlLabels': False, 'curve': 'linear', 'useMaxWidth': False},
        'sequence': {'useMaxWidth': False, 'actorFontSize': fs, 'messageFontSize': fs, 'noteFontSize': fs},
        'gantt': {'useMaxWidth': False, 'fontSize': fs, 'sectionFontSize': fs, 'axisFormat': '%m-%d', 'tickInterval': '1week'},
        'er': {'useMaxWidth': False, 'fontSize': fs},
        'state': {'useMaxWidth': False},
    }


def feishu_callouts(t):
    return {'_generated': GEN_NOTE,
            'callouts': {k: {'emoji': v['emoji'], 'background-color': v['feishu_bg'], 'border-color': v['feishu_border']} for k, v in t['callout'].items()},
            'table_header_bg': t['feishu']['table_header_bg'],
            'logo': {'width': t['feishu']['logo_width'], 'height': t['feishu']['logo_height']}}


def build(t):
    j = lambda d: json.dumps(d, ensure_ascii=False, indent=2) + '\n'
    return {'tokens.css': css(t), 'svg-palette.json': j(svg_palette(t)), 'mermaid-theme.json': j(mermaid_theme(t)), 'feishu-callouts.json': j(feishu_callouts(t))}


def main(argv):
    a = list(argv)
    if '--equiv-pt' in a:
        i = a.index('--equiv-pt')
        try:
            px, w = float(a[i + 1]), float(a[i + 2])
            cm = float(a[a.index('--content-mm') + 1]) if '--content-mm' in a else 182.0
        except (IndexError, ValueError):
            print(__doc__); return 2
        print(json.dumps({'px': px, 'viewbox_width': w, 'content_mm': cm, 'equiv_pt': round(equiv_pt(px, w, cm), 2)})); return 0
    tokens, out, check_only = TOKENS, OUT, '--check' in a
    if '--tokens' in a: tokens = os.path.abspath(a[a.index('--tokens') + 1])
    if '--out' in a: out = os.path.abspath(a[a.index('--out') + 1])
    t = json.load(open(tokens))
    errs = selfcheck(t)
    if errs:
        print(json.dumps({'ok': False, 'step': 'selfcheck', 'errors': errs}, ensure_ascii=False, indent=2)); return 1
    files = build(t)
    if check_only:
        drift = []
        for name, text in files.items():
            p = os.path.join(out, name)
            if not os.path.exists(p): drift.append(f'{name} 不存在')
            elif open(p).read() != text: drift.append(f'{name} 与 tokens.json 不一致')
        print(json.dumps({'ok': not drift, 'check': True, 'drift': drift}, ensure_ascii=False, indent=2))
        return 1 if drift else 0
    os.makedirs(out, exist_ok=True)
    for name, text in files.items():
        open(os.path.join(out, name), 'w').write(text)
    print(json.dumps({'ok': True, 'out': out, 'files': sorted(files)}, ensure_ascii=False))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
